<a href="https://colab.research.google.com/github/malinphy/Embedding_calls/blob/main/IMDB_BERT_kerasHUB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
### IMDB with BERT using keras hub connection 

In [2]:
import numpy as np 
import pandas as pd 
import tensorflow as tf 
import tensorflow_hub as hub
!pip install tensorflow_text
import tensorflow_text as text

     |████████████████████████████████| 3.4MB 7.6MB/s 


In [3]:
url  = 'https://raw.githubusercontent.com/malinphy/IMDB_Analysis_different_approachs/main/IMDB_Dataset_short2.csv'
df = pd.read_csv(url)

In [4]:
df.head(3)

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive

In [5]:
from sklearn.preprocessing import LabelBinarizer
LB = LabelBinarizer()
binary_sentiment = LB.fit_transform(df['sentiment'])
df['binary_sentiment'] = binary_sentiment
df.head(4)

review  ... binary_sentiment
0  One of the other reviewers has mentioned that ...  ...                1
1  A wonderful little production. <br /><br />The...  ...                1
2  I thought this was a wonderful way to spend ti...  ...                1
3  Basically there's a family where a little boy ...  ...                0

[4 rows x 3 columns]

In [6]:
bert_encoder = 'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-4_H-512_A-8/1'

bert_preprocessor = 'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2'

bert_tokenizer = hub.KerasLayer(bert_preprocessor)

In [7]:
text_test = ['this i such an amazing movie!']
bert_tokenizer(text_test).keys()

dict_keys(['input_type_ids', 'input_word_ids', 'input_mask'])

In [8]:
bert_tokenizer(text_test)['input_mask']

<tf.Tensor: shape=(1, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [9]:
bert_tokenizer(text_test)['input_word_ids']

<tf.Tensor: shape=(1, 128), dtype=int32, numpy=
array([[ 101, 2023, 1045, 2107, 2019, 6429, 3185,  999,  102,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0]], dtype=int32)>

In [10]:
bert_embedder = hub.KerasLayer(bert_encoder)

In [11]:
bert_embedder(bert_tokenizer(text_test)).keys()

dict_keys(['encoder_outputs', 'sequence_output', 'default', 'pooled_output'])

In [12]:
bert_embedder(bert_tokenizer(text_test))['pooled_output']

<tf.Tensor: shape=(1, 512), dtype=float32, numpy=
array([[ 0.7157584 ,  0.9987436 , -0.15102553,  0.36012033,  0.6217164 ,
         0.7098733 ,  0.97359896, -0.9864086 , -0.14171284, -0.9970235 ,
         0.10372248, -0.9788747 , -0.68936926, -0.99986273,  0.45407668,
         0.5485351 ,  0.0530567 ,  0.12715293, -0.22928238,  0.06610436,
         0.17265902, -0.05941267, -0.6126497 ,  0.8989955 ,  0.99032414,
         0.9636686 , -0.40326723, -0.10267887,  0.28981274,  0.30340227,
         0.7169639 , -0.32221377,  0.53955   , -0.44542477, -0.60813296,
         0.14418213, -0.3128127 , -0.44930103, -0.20366478, -0.06162728,
        -0.23198593, -0.16809411,  0.20032486, -0.8355514 ,  0.00881395,
        -0.5835369 , -0.9982172 ,  0.14224845,  0.5016162 , -0.40689322,
         0.9978696 , -0.44145587,  0.9871766 , -0.5643646 ,  0.01533946,
         0.11497524, -0.107868  , -0.28828543, -0.99980724, -0.9993355 ,
         0.0501882 , -0.2388813 ,  0.99482185, -0.20070581,  0.0972905 ,
 

In [13]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_labels, test_labels = train_test_split(
    df['review'],
    df['binary_sentiment'],
    train_size = 0.8,
    random_state = 42)

In [14]:
# var1 = bert_embedder(bert_tokenizer(df['review']))['pooled_output']

In [15]:
train_x.shape, train_labels.shape, test_x.shape , test_labels.shape

((15199,), (15199,), (3800,), (3800,))

In [16]:
slide_size=3000

b1 = train_x[:slide_size]
b2 = train_x[slide_size:2*slide_size]
b3 = train_x[2*slide_size:3*slide_size]
b4 = train_x[3*slide_size:4*slide_size]
b5 = train_x[4*slide_size:5*slide_size]
b6 = train_x[5*slide_size:6*slide_size]

In [17]:
b1_embeddings = bert_embedder(bert_tokenizer(b1))['pooled_output']
b2_embeddings = bert_embedder(bert_tokenizer(b2))['pooled_output']
b3_embeddings = bert_embedder(bert_tokenizer(b3))['pooled_output']
b4_embeddings = bert_embedder(bert_tokenizer(b4))['pooled_output']
b5_embeddings = bert_embedder(bert_tokenizer(b5))['pooled_output']
b6_embeddings = bert_embedder(bert_tokenizer(b6))['pooled_output']

In [18]:
b1_embeddings.shape,b2_embeddings.shape,b3_embeddings.shape,b4_embeddings.shape,b5_embeddings.shape,b6_embeddings.shape

(TensorShape([3000, 512]),
 TensorShape([3000, 512]),
 TensorShape([3000, 512]),
 TensorShape([3000, 512]),
 TensorShape([3000, 512]),
 TensorShape([199, 512]))

In [19]:
embeddings_total  = tf.concat([b1_embeddings,b2_embeddings,b3_embeddings,
           b4_embeddings,b5_embeddings,b6_embeddings],axis=0)

embeddings_total.shape

TensorShape([15199, 512])

In [21]:
model_tf = tf.keras.Sequential([
    # tf.keras.layers.Embedding(vocab_size, embedding_dim, input_length=max_length),
    # tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(1,activation='sigmoid')                    

])

In [22]:
model_tf.compile(
    loss='binary_crossentropy',
    optimizer = 'adam',
    metrics = ['accuracy']
    )

In [23]:
num_epochs =10

model_tf.fit(
    embeddings_total,
    train_labels,
    epochs=num_epochs,
    # validation_data = (testing_padded, testing_labels_final)
    batch_size = 2000
)

Epoch 1/10
8/8 [==============================] - 1s 4ms/step - loss: 0.6910 - accuracy: 0.5480
Epoch 2/10
8/8 [==============================] - 0s 4ms/step - loss: 0.6292 - accuracy: 0.6520
Epoch 3/10
8/8 [==============================] - 0s 4ms/step - loss: 0.5960 - accuracy: 0.6806
Epoch 4/10
8/8 [==============================] - 0s 4ms/step - loss: 0.5751 - accuracy: 0.7002
Epoch 5/10
8/8 [==============================] - 0s 4ms/step - loss: 0.5626 - accuracy: 0.7130
Epoch 6/10
8/8 [==============================] - 0s 4ms/step - loss: 0.5544 - accuracy: 0.7163
Epoch 7/10
8/8 [==============================] - 0s 4ms/step - loss: 0.5402 - accuracy: 0.7274
Epoch 8/10
8/8 [==============================] - 0s 4ms/step - loss: 0.5410 - accuracy: 0.7281
Epoch 9/10
8/8 [==============================] - 0s 4ms/step - loss: 0.5326 - accuracy: 0.7324
Epoch 10/10
8/8 [==============================] - 0s 3ms/step - loss: 0.5349 - accuracy: 0.7297
